name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
        
      - name: Delete previous package
        run: |
          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/ucllsoftwareengineering2324/packages/maven/be.ucll.se.groep02-backend
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build and deploy
        run: |
          mvn clean install
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download package from GitHub Packages
        run: |
          PACKAGE_URL="https://maven.pkg.github.com/UcllSoftwareEngineering2324/software-engineering-backend-groep02/be/ucll/se/groep02-backend/0.0.1/groep02-backend-0.0.1.jar"
          wget --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PACKAGE_URL -O software-engineering-backend-groep02.jar
              
      - name: Deploy to Azure Web App acceptance
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'groep2-backend-acceptance-test'
          slot-name: 'Production'
          package: 'software-engineering-backend-groep02.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C635568B4134E31851B97CEF9FA920C }}


